package Medium;

import java.util.Scanner;

public class MaximumSumSubarrays_152 {
/*
	Sample Input
	2
	4
	1 2 3 4
	3
	-10 5 10

	Sample Output
	10
	15
	
	Explanation
	For the first testcase, maximum subarray sum is generated by the entire array - 1+2+3+4 = 10
	For the second testcase , maximum subarray sum is generated by the subarray {5,10} - 5+10 = 15

*/
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner sc = new Scanner(System.in);
		int n = sc.nextInt();
		int arr[] = new int[n];
		
		for(int i = 0;i < n ; i++) {
			arr[i] = sc.nextInt();
		}
		
		System.out.println(maximumSumSubarray(arr));

	}

	private static int maximumSumSubarray(int[] arr) {
		// TODO Auto-generated method stub
		int currSum =0;
		int maxSum = 0;
		for(int i=0;i<arr.length;i++) {
			currSum+=arr[i];
			if(currSum<0) {
				currSum=0;
			}
			else if( currSum > maxSum) {
				maxSum = currSum; 
			}
		}
		return maxSum;
		
	}

}
